name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocs-glightbox
      - run: pip install pymdown-extensions
      - run: pip3 install mkdocs-pdf-export-plugin
      - run: pip3 install weasyprint
      - run: mkdocs gh-deploy --force
